### ISSUE TITLE
ObjectId unknown type

### ISSUE THREAD

**Issue by dkebler** [BenZed/feathers-schema#2]
obviously a priori node doesn't know that `ObjectId` is a derived type 

I see that you exported `types` so I assume your example in the section on services should be as below.  Are the default types, like `String` unaltered?  If they are then this would apply for other types as well.
```
const { Schema, types } = require('feathers-schema');

new Schema({
  essay: String,
  author: { type: types.ObjectId, service: 'authors' },
  comments: [{ type: ObjectId, service: 'comments'}]
})
```
----BTW

This is a great project/repo!  I was looking looking looking for some way to incorporate a schema what would work with NeDB or other dbs supported by feathers.  I need tot primarily to initialize/populate document/object instances (as vue needs to have object's properties/keys to initially exist to be reactive).  

Plus your module has the hooks built in.  I get sanitizing and validating too.

And I can use the schemas in the front end hopefully with vuelidate

What's not to like!

Since you've given me such a head start can I help out?  How about a PR for this change in documentation?

I see this other topics... what can I help with there?
```
Schema Options
//TODO: finish this example once options finalized.

Custom Types

//TODO: finish this example once custom types are fleshed out.

Associations

//TODO: finish this example once associations are fleshed out.

Further Considerations
```

**Comment by BenZed** [comment]
Well, the types export also contains functionality to inject your own types, but this hasn't been tested.

How I'm handling ObjectId (and perhaps types in general) needs to be rethought.

By default, the ObjectId type is imported from 'bson-objectid', because I don't want *mongod* to be a dependency. Which is silly because the whole reason I'm supplying them at all is so that I supply the same types that *mongoose* does by default, in the first place.

(I also import 'buffer' so that a Buffer type is exposed if this module is used in the browser.)

Problem is, I'm doing type comparisons with _instanceof_, and an object of type BsonObjectId is not an instance of MongodObjectId. This generally doesn't cause a problem because *feathers-schema* does the necessary type coercions to and from the database in the sanitize method, but it feels like terrible practice and can cause _hard-to-debug_ gotchas for the layman trying to create schemas.

I'm thinking ObjectId and Buffer should be removed as default types, and if you want to use them, you'll have to set them as custom types. This way you can use whatever implementation of ObjectId or Buffer (or whatever other type, for that matter) you like.

Either that, or come up with something that doesn't use JavaScript constructors at all. Set up something similar to how *sequelize* or *mongod* does it. Or perhaps figure out something using the 'prop-types' module.

What do you think?

----

Also, thank you for your kind words!

I'm a HUGE fan of feathers, and I've got this and a number of other feathers packages on the go for an app I'm building at work. It's been difficult to get them on track to their respective version 1's at a reasonable pace.

Honestly, the biggest help (especially for this repo) would be testing. The current test code is an incomplete dog's breakfast. There are no client side tests or tests for any  database adapters. (Other than _feathers-memory_)

Additionally, perhaps feedback on signatures for creating custom validators and sanitizers. Right now it feels like it's a bit verbose to create custom validators that will properly work client-side and server-side.

Also, what do you recommend for creating API documentation? I haven't done too much research into this, so I'm sure there's something standard (like JsDoc) but I feel like writing everything into the README the way I'm doing it is inefficient.

**Comment by dkebler** [comment]
In my feathers naivete (only been coding with it for a few weeks) it seems no reason to type the ObjectID.   If you need to refer to the id of a document of another service in your schema then just use a plain `String` type for that property.  In my way of thinking feather's db adaptors "hide" the actual db goings  on with common CRUD calls.  I just make a feathers call (e.g.  get) with a string for ID and I get the document I want back.   So if someone wants something more db specific yea they could make their own custom type.

FYI I use used this repo for custom type checking like of my classes.   https://github.com/bevry/typechecker/issues/15

This guy writes really nice clean code and he has a documentation package he calls docma.  It uses jsdoc in your code and makes super nice API documentation and guide.  http://onury.io/docma/
check out one of his other projects where he uses it.  http://onury.io/tasktimer/?api=tasktimer

I can do some testing via trying to use the repo in my project (a lighting control project using quasar, vue, feathers, and nedb).  Then I could work on some actual tests.   Probably not much time the rest of Sept. but I have set aside October for doing a bunch of coding on my project and thus on your repo as well.

As to what I hoped feathers-schema would do for me.....I have discovered that using either the sanitizer or populator feathers-schema hooks won't create corresponding properties in a document if the schema property has a default value.  That is actually what I hoped it would do.  When user clicks on quasar/vue button to add a device (i.e. document) I need to create a "filled in" document in feathers server with all properties having a default value and then `get` that back to quasar/vue component's v-model object or it doesn't display/work properly (without all the keys/properties already existing.)
I kinda played around with feathers-schema today attaching new schemas to the service but I can't grab the default properties as they are part of a Symbol and being new to JS Symbols I'm not sure how to fetch it.  Guess it's time to hit the books.  If I can get this figured out then it could be added as a feature of populate or as a separate hook `initialize` maybe?

**Comment by BenZed** [comment]
non standard types have been removed as of latest version
