### ISSUE TITLE
enhancement - default instance of schema

### ISSUE THREAD

**Issue by dkebler** [BenZed/feathers-schema#3]
thought I would open separate issue for this.

First I couldn't find a method in your schema class to easily return the schema/property/object but I did figure out a way to get it via the `definition` symbol (not grokking why symbols were needed really, nor the `parent` symbol). 
```
  let defaults = {};
  for (let property of myschema.properties) {
    let propDefault = property[Object.getOwnPropertySymbols(property)[1]];
   // should skip any unique property
    if (!propDefault.unique) {
      defaults[property.key] =  propDefault.default ? propDefault.default : new propDefault.type;
    }
  }
```

I cobbled together my own `initialize`  hook using the above and that works for me.

but

https://github.com/BenZed/feathers-schema/blob/master/src/hooks/populate-with-schema.js

I see that the feathers-schema populate hook uses a call to `fillwithproperties` function that takes a `fill` argument.  If I read your code right the `fill` argument comes from reading a document from the db (would be empty if create had been called).   What if the populate hook had an option boolean flag `init`.   In which case the hook would only proceed for `create` and the `defaults` object from above would be passed instead of an existing document contents.  If any schema properties were set as unique then they would have to have data keys sent from client and could even be checked for existence/uniqueness at this point.

*If that seems like a workable approach then I'll fork and branch and work on a PR for that*

**related questions:**
 not sure why one has to pass a schema to the hook as an option when the hook was attached to the schema in the first place.  Can it be bound?   I had attached the schema(s) to the model or directly to the service object for later access.  In which case no need to pass them.

 `service` is a property of the hook so why the `const service = this` ?   when it could be `const { method, type, data, service } = hook.   Kinda confused is one way or the other being deprecated in feathers? 

BTW I have more than one document schema per database/service (e.g. my hardware database/service has hardware types and instance of those types in the same service).  Each document has a property for which schema type.  Thus in the hooks if it looked in the data or params for the document type and then used the corresponding schema what would be another enhancement.

**Comment by BenZed** [comment]
## Definition
Funny you should mention, I just added a getter for 'definition' in my last commit. (Haven't pushed it yet).

That said, you could just do it in reverse:

`
const definition = {
    name: { type: String, default: 'dkeblr' } 
}

export default new Schema(definition)
export { definition }

`
---
## Populate Hook

The populate hook only fires during a *patch* service call. It doesn't throw an error in *patch* or *create* for convenience. It's real only purpose is to populate fields that might be required by cross validations, so that they don't incorrectly pass or fail on complete data. Consider:
`
const ifNoEmail = (value, {data}) => !data.email

export default new Schema ({

  name: { type: String, required: ifNoEmail },
  email: { type: String }

})
`
In the above example, if we were to make a patch that _removed_ the name of some user:
`
const someId = 0
service('users').patch(someId, { name: null })
`
Without the populate hook, this would result in a validation error, even if the user had a name stored in the database.

This does mean that the populate hook could fire on schemas that don't need to consider cross-validations, but advanced users could simply omit the populate hook.

If you're trying to get an object that holds any default values defined by the schema, what you want to run is the sanitize hook, or the schema's sanitize method:

`const carSchema = new Schema({

  wheels: { type: Number, default: 4 },
  model: { type: String, default: 'hatchback' }

})

carSchema
  .sanitize({}) // sanitize an empty object
  .then(data => console.log(data)) // { wheels: 4, model: 'hatchback' }
`
Now, I'm wondering what problem your suggestion was trying to solve, as this should be the default behaviour. Are you creating documents, and their default data isn't being created?

---
## Why does the schema have to be passed to the hook as an option?

It doesn't! The hooks in schema.hooks already have the schema's bound to them. Part of the schema's constructor looks like this:
`
    // Build Hooks
    this.hooks.populate = populateWithSchema(this)
    this.hooks.validate = validateWithSchema(this)
    this.hooks.sanitize = sanitizeWithSchema(this)
`
If you're wondering why the hooks are placed into their own folder, that's just an organizational thing. I wrote them as with the idea that a Schema's logic and behaviour is a separate concern from it's usage in feathers. Right now there's no reason to import the hooks and supply schemas to them, but there may be in the future if there is some configuration that could be supplied to hooks that shouldn't apply to Schemas.

## const service = this

I did not know that the hook had a service field! Is that new? When written as a dynamically scoped function, hooks are run with the service as 'this', but i'll make this change in the refactor, as it's much more readable. Thanks!

## variable schema types
I was thinking of adding some sort of functionality like this. Variable properties, or variable schemas. Good suggestion!

**Comment by BenZed** [comment]
latest version has a 'definition' getter
